package main

import (
	"bytes"
	"crypto/sha256"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"time"
)

// This test is fully generated by LLM.

func TestGetEnv(t *testing.T) {
	t.Run("should return the value of the environment variable", func(t *testing.T) {
		os.Setenv("TEST_ENV", "test")
		if GetEnv("TEST_ENV", "default") != "test" {
			t.Errorf("GetEnv returned %s, expected %s", GetEnv("TEST_ENV", "default"), "test")
		}
	})
}

func TestUploadTaskOutput(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv(storageDirKey, tmpDir)
	defer os.Unsetenv(storageDirKey)

	t.Run("should upload file successfully", func(t *testing.T) {
		req := httptest.NewRequest("PUT", "/v1/cache/testhash", bytes.NewBufferString("test content"))
		req.Header.Set("Content-Length", "12")
		req.SetPathValue("hash", "testhash")
		w := httptest.NewRecorder()

		UploadTaskOutput(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}

		filePath := filepath.Join(tmpDir, "testhash.cache")
		if _, err := os.Stat(filePath); os.IsNotExist(err) {
			t.Error("file was not created")
		}
	})

	t.Run("should return error when Content-Length is missing", func(t *testing.T) {
		req := httptest.NewRequest("PUT", "/v1/cache/testhash2", bytes.NewBufferString("test"))
		req.SetPathValue("hash", "testhash2")
		w := httptest.NewRecorder()

		UploadTaskOutput(w, req)

		if w.Code != http.StatusBadRequest {
			t.Errorf("expected status %d, got %d", http.StatusBadRequest, w.Code)
		}
	})

	t.Run("should return error when file already exists", func(t *testing.T) {
		filePath := filepath.Join(tmpDir, "existing.cache")
		os.WriteFile(filePath, []byte("existing"), 0644)

		req := httptest.NewRequest("PUT", "/v1/cache/existing", bytes.NewBufferString("new content"))
		req.Header.Set("Content-Length", "11")
		req.SetPathValue("hash", "existing")
		w := httptest.NewRecorder()

		UploadTaskOutput(w, req)

		if w.Code != http.StatusConflict {
			t.Errorf("expected status %d, got %d", http.StatusConflict, w.Code)
		}
	})
}

func TestDownloadTaskOutput(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv(storageDirKey, tmpDir)
	defer os.Unsetenv(storageDirKey)

	t.Run("should download file successfully", func(t *testing.T) {
		filePath := filepath.Join(tmpDir, "testhash.cache")
		os.WriteFile(filePath, []byte("test content"), 0644)

		req := httptest.NewRequest("GET", "/v1/cache/testhash", nil)
		req.SetPathValue("hash", "testhash")
		w := httptest.NewRecorder()

		DownloadTaskOutput(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}
		if w.Body.String() != "test content" {
			t.Errorf("expected body 'test content', got '%s'", w.Body.String())
		}
	})

	t.Run("should return error when file not found", func(t *testing.T) {
		req := httptest.NewRequest("GET", "/v1/cache/nonexistent", nil)
		req.SetPathValue("hash", "nonexistent")
		w := httptest.NewRecorder()

		DownloadTaskOutput(w, req)

		if w.Code != http.StatusNotFound {
			t.Errorf("expected status %d, got %d", http.StatusNotFound, w.Code)
		}
	})
}

func TestCheckBearerTokenMiddleware(t *testing.T) {
	handler := func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusOK)
	}

	t.Run("should allow request when no token is configured", func(t *testing.T) {
		os.Unsetenv(authTokenKey)
		middleware := CheckBearerTokenMiddleware(mustLoadAuthTokens(t), handler)

		req := httptest.NewRequest("GET", "/", nil)
		w := httptest.NewRecorder()

		middleware(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}
	})

	t.Run("should allow request with valid token", func(t *testing.T) {
		os.Setenv(authTokenKey, "test-token")
		defer os.Unsetenv(authTokenKey)
		middleware := CheckBearerTokenMiddleware(mustLoadAuthTokens(t), handler)

		req := httptest.NewRequest("GET", "/", nil)
		req.Header.Set("Authorization", "Bearer test-token")
		w := httptest.NewRecorder()

		middleware(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}
	})

	t.Run("should reject request with invalid token", func(t *testing.T) {
		os.Setenv(authTokenKey, "test-token")
		defer os.Unsetenv(authTokenKey)
		middleware := CheckBearerTokenMiddleware(mustLoadAuthTokens(t), handler)

		req := httptest.NewRequest("GET", "/", nil)
		req.Header.Set("Authorization", "Bearer wrong-token")
		w := httptest.NewRecorder()

		middleware(w, req)

		if w.Code != http.StatusUnauthorized {
			t.Errorf("expected status %d, got %d", http.StatusUnauthorized, w.Code)
		}
	})

	t.Run("should reject request without Authorization header", func(t *testing.T) {
		os.Setenv(authTokenKey, "test-token")
		defer os.Unsetenv(authTokenKey)
		middleware := CheckBearerTokenMiddleware(mustLoadAuthTokens(t), handler)

		req := httptest.NewRequest("GET", "/", nil)
		w := httptest.NewRecorder()

		middleware(w, req)

		if w.Code != http.StatusUnauthorized {
			t.Errorf("expected status %d, got %d", http.StatusUnauthorized, w.Code)
		}
	})
}

func TestHandleHealth(t *testing.T) {
	req := httptest.NewRequest("GET", "/health", nil)
	w := httptest.NewRecorder()

	HandleHealth(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
	}
	if w.Body.String() != "OK" {
		t.Errorf("expected body 'OK', got '%s'", w.Body.String())
	}
}

func TestHandleTask(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv(storageDirKey, tmpDir)
	defer os.Unsetenv(storageDirKey)

	t.Run("should handle PUT request", func(t *testing.T) {
		req := httptest.NewRequest("PUT", "/v1/cache/testhash", bytes.NewBufferString("test"))
		req.Header.Set("Content-Length", "4")
		req.SetPathValue("hash", "testhash")
		w := httptest.NewRecorder()

		HandleTask(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}
	})

	t.Run("should handle GET request", func(t *testing.T) {
		filePath := filepath.Join(tmpDir, "testhash2.cache")
		os.WriteFile(filePath, []byte("test"), 0644)

		req := httptest.NewRequest("GET", "/v1/cache/testhash2", nil)
		req.SetPathValue("hash", "testhash2")
		w := httptest.NewRecorder()

		HandleTask(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}
	})

	t.Run("should handle HEAD request", func(t *testing.T) {
		filePath := filepath.Join(tmpDir, "testhash3.cache")
		os.WriteFile(filePath, []byte("test"), 0644)

		req := httptest.NewRequest("HEAD", "/v1/cache/testhash3", nil)
		req.SetPathValue("hash", "testhash3")
		w := httptest.NewRecorder()

		HandleTask(w, req)

		if w.Code != http.StatusOK {
			t.Errorf("expected status %d, got %d", http.StatusOK, w.Code)
		}

		if w.Body.String() != "" {
			t.Errorf("expected body '', got '%s'", w.Body.String())
		}
	})

	t.Run("should reject unsupported method", func(t *testing.T) {
		req := httptest.NewRequest("POST", "/v1/cache/testhash", nil)
		req.SetPathValue("hash", "testhash")
		w := httptest.NewRecorder()

		HandleTask(w, req)

		if w.Code != http.StatusMethodNotAllowed {
			t.Errorf("expected status %d, got %d", http.StatusMethodNotAllowed, w.Code)
		}
	})
}

func TestInvalidHashRejected(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv(storageDirKey, filepath.Join(tmpDir, "storage"))
	defer os.Unsetenv(storageDirKey)
	os.Mkdir(filepath.Join(tmpDir, "storage"), 0755)
	os.WriteFile(filepath.Join(tmpDir, "secret.cache"), []byte("secret"), 0644)

	hashes := []string{"../secret", "../../etc/x", "a/b", `a\b`, "..", ".", "", "a.b", strings.Repeat("a", 129)}
	for _, method := range []string{"PUT", "HEAD", "GET"} {
		for _, hash := range hashes {
			req := httptest.NewRequest(method, "/v1/cache/x", bytes.NewBufferString("pwned"))
			req.Header.Set("Content-Length", "5")
			req.SetPathValue("hash", hash)
			w := httptest.NewRecorder()

			HandleTask(w, req)

			if w.Code != http.StatusBadRequest {
				t.Errorf("%s %q: expected status %d, got %d", method, hash, http.StatusBadRequest, w.Code)
			}
		}
	}

	if _, err := os.Stat(filepath.Join(tmpDir, "x.cache")); !os.IsNotExist(err) {
		t.Error("file was created outside the storage directory")
	}
}

func TestPathTraversalThroughRouter(t *testing.T) {
	tmpDir := t.TempDir()
	os.Setenv(storageDirKey, filepath.Join(tmpDir, "storage"))
	defer os.Unsetenv(storageDirKey)
	os.Mkdir(filepath.Join(tmpDir, "storage"), 0755)
	os.WriteFile(filepath.Join(tmpDir, "secret.cache"), []byte("secret"), 0644)

	mux := http.NewServeMux()
	mux.HandleFunc("/v1/cache/{hash}", HandleTask)

	req := httptest.NewRequest("GET", "/v1/cache/..%2Fsecret", nil)
	w := httptest.NewRecorder()
	mux.ServeHTTP(w, req)

	if w.Code != http.StatusBadRequest {
		t.Errorf("expected status %d, got %d (body %q)", http.StatusBadRequest, w.Code, w.Body.String())
	}
}

func mustLoadAuthTokens(t *testing.T) map[[32]byte]string {
	t.Helper()
	tokens, err := loadAuthTokens()
	if err != nil {
		t.Fatalf("loadAuthTokens: %v", err)
	}
	return tokens
}

func TestLoadAuthTokens(t *testing.T) {
	hash := func(s string) [32]byte { return sha256.Sum256([]byte(s)) }

	tests := []struct {
		name       string
		authToken  string
		authTokens string
		want       map[[32]byte]string
		wantErr    bool
	}{
		{name: "no variables set", want: nil},
		{name: "AUTH_TOKEN only", authToken: "tok", want: map[[32]byte]string{hash("tok"): ""}},
		{
			name:       "AUTH_TOKENS with two entries",
			authTokens: "repoA:tokA, repoB : tokB",
			want:       map[[32]byte]string{hash("tokA"): "repoA", hash("tokB"): "repoB"},
		},
		{
			name:       "token containing colon",
			authTokens: "repoA:tok:with:colons",
			want:       map[[32]byte]string{hash("tok:with:colons"): "repoA"},
		},
		{name: "both variables set", authToken: "tok", authTokens: "repoA:tokA", wantErr: true},
		{name: "bad name", authTokens: "../x:tok", wantErr: true},
		{name: "duplicate name", authTokens: "repoA:tok1,repoA:tok2", wantErr: true},
		{name: "duplicate token", authTokens: "repoA:tok,repoB:tok", wantErr: true},
		{name: "malformed entry", authTokens: "foo", wantErr: true},
		{name: "empty entry", authTokens: "repoA:tokA,,repoB:tokB", wantErr: true},
		{name: "missing token", authTokens: "repoA:", wantErr: true},
		{name: "missing name", authTokens: ":tok", wantErr: true},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Setenv(authTokenKey, tt.authToken)
			t.Setenv(authTokensKey, tt.authTokens)

			got, err := loadAuthTokens()
			if tt.wantErr {
				if err == nil {
					t.Fatalf("expected error, got %v", got)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("got %v, want %v", got, tt.want)
			}
		})
	}
}

func TestNamespaceIsolation(t *testing.T) {
	storageDir := t.TempDir()
	t.Setenv(storageDirKey, storageDir)
	t.Setenv(authTokenKey, "")
	t.Setenv(authTokensKey, "repoA:tokA,repoB:tokB")
	for _, ns := range []string{"repoA", "repoB"} {
		os.Mkdir(filepath.Join(storageDir, ns), 0755)
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/v1/cache/{hash}", CheckBearerTokenMiddleware(mustLoadAuthTokens(t), HandleTask))

	do := func(method, token, body string) *httptest.ResponseRecorder {
		req := httptest.NewRequest(method, "/v1/cache/abc123", strings.NewReader(body))
		req.Header.Set("Authorization", "Bearer "+token)
		if method == "PUT" {
			req.Header.Set("Content-Length", strconv.Itoa(len(body)))
		}
		w := httptest.NewRecorder()
		mux.ServeHTTP(w, req)
		return w
	}

	if w := do("PUT", "tokA", "contentA"); w.Code != http.StatusOK {
		t.Fatalf("repoA upload: expected %d, got %d", http.StatusOK, w.Code)
	}
	if w := do("HEAD", "tokB", ""); w.Code != http.StatusNotFound {
		t.Errorf("repoB HEAD: expected %d, got %d", http.StatusNotFound, w.Code)
	}
	if w := do("GET", "tokB", ""); w.Code != http.StatusNotFound {
		t.Errorf("repoB GET: expected %d, got %d", http.StatusNotFound, w.Code)
	}
	if w := do("PUT", "tokB", "contentB"); w.Code != http.StatusOK {
		t.Fatalf("repoB upload: expected %d, got %d", http.StatusOK, w.Code)
	}
	if w := do("GET", "tokA", ""); w.Code != http.StatusOK || w.Body.String() != "contentA" {
		t.Errorf("repoA GET: got %d %q", w.Code, w.Body.String())
	}
	if w := do("GET", "tokB", ""); w.Code != http.StatusOK || w.Body.String() != "contentB" {
		t.Errorf("repoB GET: got %d %q", w.Code, w.Body.String())
	}
	if w := do("GET", "unknown", ""); w.Code != http.StatusUnauthorized {
		t.Errorf("unknown token: expected %d, got %d", http.StatusUnauthorized, w.Code)
	}

	for _, p := range []string{"repoA/abc123.cache", "repoB/abc123.cache"} {
		if _, err := os.Stat(filepath.Join(storageDir, p)); err != nil {
			t.Errorf("expected %s to exist: %v", p, err)
		}
	}
	if _, err := os.Stat(filepath.Join(storageDir, "abc123.cache")); !os.IsNotExist(err) {
		t.Error("file was written to the flat storage directory")
	}
}

func TestCleanupNamespacedFiles(t *testing.T) {
	storageDir := t.TempDir()
	t.Setenv(storageDirKey, storageDir)
	nsDir := filepath.Join(storageDir, "repoA")
	os.Mkdir(nsDir, 0755)

	oldFile := filepath.Join(nsDir, "old.cache")
	newFile := filepath.Join(nsDir, "new.cache")
	os.WriteFile(oldFile, []byte("old"), 0644)
	os.WriteFile(newFile, []byte("new"), 0644)
	past := time.Now().Add(-2 * time.Hour)
	if err := os.Chtimes(oldFile, past, past); err != nil {
		t.Fatal(err)
	}

	cleanupOldRecords(time.Hour)

	if _, err := os.Stat(oldFile); !os.IsNotExist(err) {
		t.Error("expected old namespaced file to be removed")
	}
	if _, err := os.Stat(newFile); err != nil {
		t.Errorf("expected new namespaced file to remain: %v", err)
	}
}
